name: Readme CI

on:
  push:
    branches: master
  workflow_dispatch:
  schedule:
  - cron: '0 0 */1 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Update Readme Page
      run: node app/readme.js > README.md
    - name: Sync Repository
      run: |
          git config user.name 'amirisback'
          git config user.email 'faisalamircs@gmail.com'
          git commit -am "Update README.md
          
          
          Co-authored-by: frogoboxbot <frogoboxmedia@gmail.com>
          Co-authored-by: Hudio Hizari <hhizari@gmail.com>
          Co-authored-by: castariva18 <tengku13elmiro@gmail.com>
          Co-authored-by: fiqryq <fiqrychoerudin48@gmail.com>
          Co-authored-by: feronikanm <firaferonika27@gmail.com>
          Co-authored-by: bryanrafsanzani <bryanrafsanzani46@gmail.com>
          "
          git push
