name: Plant Tree CI

on:
  push:
    branches: master
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: plant a tree in the garden
      run: node garden.js > GARDEN.md
    - name: Commit change & Push
      run: |
          git config user.name 'amirisback'
          git config user.email 'faisalamircs@gmail.com'
          git commit -am "plant some tree 🌳"
          git push