name: Plant Tree CI

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * */3'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Plant a tree in the garden
      run: node app/garden.js > GARDEN.md
    - name: Sync Repository
      run: |
          git config user.name 'amirisback'
          git config user.email 'faisalamircs@gmail.com'
          git pull
          git commit -am "Plant some tree 🌳"
          git push
